apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: real-estate-for-all-canary
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: real-estate-for-all
  type: ClusterIP
status:
  loadBalancer: {}
